---
deployment:
  tasks:
    - export DEPLOYPATH=/home1/aakai5l8/peoplenex.online

    # Sync repository to deployment directory
    - /usr/bin/rsync -av --delete --exclude=".git" ./ $DEPLOYPATH/

    # Laravel
    - cd $DEPLOYPATH
    - composer install --no-dev --prefer-dist --optimize-autoloader
    - php artisan migrate --force
    - php artisan optimize:clear
    - php artisan optimize
